version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/parabrola/goke/internal.CURRENT_VERSION={{.Version}}
brews:
  - name: goke
    homepage: https://github.com/parabrola/goke
    description: "Build automation tool using YAML"
    tap:
      owner: parabrola
      name: homebrew-goke
scoops:
  - bucket:
      owner: parabrola
      name: scoop-goke
    homepage: https://github.com/parabrola/goke
    description: "Build automation tool using YAML"
nfpms:
  - package_name: goke
    homepage: https://github.com/parabrola/goke
    maintainer: Parabrola <noreply@parabrola.com>
    description: "Build automation tool using YAML"
    formats:
      - deb
      - rpm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
