name: Run CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.x
    - run: "test -z \"$(gofmt -l .)\""
    - run: "go vet ./..."
    - run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum
    - run: "go test ./..."
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "latest"
        install-go: false
